config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'

  get 'purchase/done'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"

  resources :questions, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get 'search'
    end
    resources :answers, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end 
  resources :cards, only: [:new, :create] do
  end
  
  resources :items, only: [:index, :new, :show, :create] do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord

  has_many :answers
  belongs_to :user
  
  validates :contents, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
  def self.search(search)
    return Question.all unless search
    Question.where('contents LIKE(?)', "%#{search}%")
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController 
  
  def index
    @questions = Question.includes(:user).order("created_at DESC")
  end

  def new
    @question = Question.new
  end

  def create
    # binding.pry
    @question = Question.create(question_params)
    @question.save
    redirect_to root_path
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @answers = @question.answers.includes(:user)
    @like = Like.new
  end

  def destroy
    question = Question.find(params[:id])
    if  question.destroy
      redirect_to root_path
    else 
      render :show
    end
  end

  def search
    @questions = Question.search(params[:keyword])
  end
  

 private
 def question_params
  # binding.pry
  # params[:question].permit(:image, :contents, :title, :price).merge(user_id: current_user.id)
  params.require(:post).permit(:image, :contents, :title, :price).merge(user_id: current_user.id)
 end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_new.html.haml
-# = render partial: 'post'
-# = render partial: 'questions/post'

.main-contents
  
  .main-contents__question
    = form_for questions_path do |f|
      .main-contents__question--top 
        タイトル  
      = f.text_field :title, class: "main-contents__question--title", placeholder: '　タイトルを入力してください'
      .main-contents__question--main 
        本文
      = f.text_area :contents, class: "main-contents__question--text", placeholder: '　質問を入力してください'
      = f.label :image, class: "main-contents__question--image" do
        = icon("fas", "image")
        = f.file_field :image, class: "main-contents__question--image--file"
      = f.submit "投稿", class: "main-contents__question--btn"
      
    

app/views/questions/_post.html.haml
%header
  .header-logo
    =link_to "TIM", root_path, class:"header-logo__title"
    %p
      − Time Is Money - 
  %ul.header-list 
    -if user_signed_in?
      %li= link_to current_user.name, "#", class: "header-list__li"
      %li= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-list__li"
      %li= link_to "質問する", items_path, class: "header-list__li"
      -# %ul.header-list__drop
      -#   質問する
      -#   -# %li= link_to Item.find(1).name , items_path,class:"header-list__drop--list"
      -#   -# -@items.each do |item|
      -#   -#   =link_to item.name, "#"
      -#   -# %li= render partial: "items/index" 
      -#   %li= link_to "1000円の質問をする", items_path,class:"header-list__drop--list"
      -#   %li= link_to "1500円の質問をする", "#",class:"header-list__drop--list"
      
    -else
      %li= link_to "ログイン", new_user_session_path, class: "header-list__li"

      %li= link_to "新規登録", new_user_registration_path, class: "header-list__li"
    
    
      
  

.side
   
  .side__top
    = link_to "質問一覧", root_path
  .side__title
    カテゴリー

  .side__list
    プログラミング
  
  .side__list
    筋トレ
  
  = form_tag( "/questions/search", method: :get , class: "search-form") do
    = text_field_tag :keyword, params[:keyword],{placeholder: "質問を検索する",class:"search-form__text"}
    = submit_tag "検索",class:"search-form__submit"

app/views/questions/index.html.haml
= render partial: 'post'

-# cssは_questions.scss
.main-contents
    
  - @questions.each do |question|
    .main-contents__content
      = link_to "a", question_path(question.id)
      .main-contents__content--info 
        .main-contents__content--info--title
          = question.title
          -# = link_to question.title, question_path(question.id)
        .main-contents__content--info--name
          = "質問者:　#{question.user.name}"
        .main-contents__content--info--price
          = question.price
      .main-contents__content--main.clearfix    
        .main-contents__content--main--text
          = question.contents 
        .main-contents__content--main--image
          -if question.image?
            ※画像が投稿されています
        .main-contents__content--main--time
          = question.created_at
  
    

app/views/questions/new.html.haml
= render partial: 'post'

.main-contents
  
  .main-contents__question
    = form_for @question do |f|
      .main-contents__question--top 
        タイトル  
      = f.text_field :title, class: "main-contents__question--title", placeholder: '　タイトルを入力してください'
      .main-contents__question--main 
        本文
      = f.text_area :contents, class: "main-contents__question--text", placeholder: '　質問を入力してください'
      = f.label :image, class: "main-contents__question--image" do
        = icon("fas", "image")
        = f.file_field :image, class: "main-contents__question--image--file"
      = f.submit "投稿", class: "main-contents__question--btn"

app/views/questions/search.html.haml
= render partial: 'post'

-# cssは_questions.scss
.main-contents
  -# = form_tag( "/questions/search", method: :get , class: "search-form") do
  -#   = text_field_tag :keyword, params[:keyword],{placeholder: "質問を検索する",class:"search-form__text"}
  -#   = submit_tag "検索",class:"search-form__submit"
  - @questions.each do |question|
    .main-contents__content
      = link_to "a", question_path(question.id)
      .main-contents__content--info 
        .main-contents__content--info--title
          = question.title
          -# = link_to question.title, question_path(question.id)
        .main-contents__content--info--name
          = "質問者:　#{question.user.name}"
        .main-contents__content--info--price
          = question.price
      .main-contents__content--main.clearfix    
        .main-contents__content--main--text
          = question.contents 
        .main-contents__content--main--image
          -if question.image?
            ※画像が投稿されています
        .main-contents__content--main--time
          = question.created_at
  
    

app/views/questions/show.html.haml
= render partial: 'post'

.main-contents
    
  .main-contents__show
    .main-contents__show--info 
      .main-contents__show--info--title
        = @question.title
        -#  link_to question.title, question_path(@questions.ids)
      .main-contents__show--info--name
        = @question.user.name
      .destroy_btn
        -if user_signed_in?
          -if @question.user_id == current_user.id || current_user.email == "yujiasano@yujiasano"  
            = icon("fas","trash-alt")    
            = link_to "投稿を削除", question_path(@question.id), method: "DELETE", data: {confirm: "この作業は取り消せません。本当に削除しますか？"}
      -# .main-contents__show--info--like
      -#   = button_to "いいね", question_answers_path(@question.id)
    .main-contents__show--main.clearfix    
      .main-contents__show--main--text
        = @question.contents
      .main-contents__show--main--image
        = image_tag @question.image     
      .main-contents__show--main--time
        = @question.created_at

  .main-contents__answer

    = render partial: 'answers/answer'

  -# .answers
  -#   = if current_user
  -#     .input-box
  -#       %input{type: "text", class}
    -#   = form_with(model: [@tweet, @comment], local: true) do |form| %>
    -#     <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
    -#     <%= form.submit "SEND" %>
    -#   <% end %>
    -# <% else %>
    -#   <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    -# <% end %>