config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'

  get 'purchase/done'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"

  resources :questions, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get 'search'
    end
    resources :answers, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end 
  resources :cards, only: [:new, :create] do
  end
  
  resources :items, only: [:index, :new, :show, :create] do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_one :like

  validates :text, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
  def like_user(user_id)
    Like.find_by(user_id: user_id)
   end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # def index
  #   @answers = Answer.includes(:user,:question)
  # end
  
  # def new
  #   @answer = Answer.new
  # end

  def create
    # binding.pry
    @answer = Answer.create(answer_params)
    redirect_to question_path(@answer.question.id)
    @like = Like.new
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
  end

  


  private
  def answer_params
    params.require(:answer).permit(:text, :image).merge(user_id: current_user.id, question_id: params[:question_id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
- if @answers 
  .main-contents__text
    −−−−−−−−−−−−−   回答一覧   −−−−−−−−−−−−−
  - @answers.each do |answer|
    .main-contents__show
      .main-contents__show--info.clearfix  
      -# .main-contents__show--info--title
      -#   = @question.title
        -#  link_to question.title, question_path(@questions.ids)
      .main-contents__show--info--name
        = answer.user.name
        -# = render partial: 'likes/like', locals: { answer: @answer, answers: @answers}
      .main-contents__show--info--fav
        =render partial: "likes/like", locals: { answer: answer}
      -# .main-contents__show--info--fav
      -#   -if @question.user.already_liked?(answer)
      -#     .liked
      -#       =link_to icon("fas", "crown"), question_answer_like_path(@question.id, answer.id, params[:id]), method:"DELETE"
      -#       -# = icon("fas", "crown")

      -#   -elsif current_user == @question.user 
      -#     .like
      -#       = link_to icon("fas", "crown"), question_answer_likes_path(@question.id,answer.id), method:"POST", class: "like-btn"
        
          
      .main-contents__show--main.clearfix 
         
        .main-contents__show--main--text
          = raw Rinku.auto_link(h(answer.text))
          -# text_url_to_link(h(answer.text)).html_safe
        .main-contents__show--main--image
          = image_tag answer.image     
        .main-contents__show--main--time
          = answer.created_at
-# -else
-#   .main-contents__text
-#     −−−−−−−−−−−−−   回答はまだありません   −−−−−−−−−−−−−

-if user_signed_in?
  .main-contents__question
    = form_for [@question,@answer] do |f|
      -# .main-contents__question--top 
      -#   タイトル  
      -# = f.text_field :title, class: "main-contents__question--title", placeholder: '　タイトルを入力してください'
      .main-contents__question--main 
        回答
      = f.text_area :text, class: "main-contents__question--text", placeholder: '　回答を入力してください', value: ""
      = f.label :image, class: "main-contents__question--image" do
        = icon("fas", "image")
        = f.file_field :image, class: "main-contents__question--image--file",value: ""
      = f.submit "投稿", class: "main-contents__question--btn"