config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'

  get 'purchase/done'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"

  resources :questions, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get 'search'
    end
    resources :answers, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end 
  resources :cards, only: [:new, :create] do
  end
  
  resources :items, only: [:index, :new, :show, :create] do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  # def index
  #   @item = Item.find()
  # end


  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
def index
  @items = Item.all
end

def new
  @item = Item.new
end

def show
  @item = Item.find(params[:id])
end

def create
  # binding.pry
  @item = Item.create(item_params)
  redirect_to root_path
end

# def pay
#   # binding.pry
#   @item = Item.find(params[:id])
#   card = Card.where(user_id: current_user.id).first
#   Payjp.api_key = ENV['PAYJP_SECRET_KEY']
#   Payjp::Charge.create(
#   :amount => @item.price, #支払金額を入力（itemテーブル等に紐づけても良い）
#   :customer => card.customer_id, #顧客ID
#   :currency => 'jpy', #日本円
# )
# redirect_to action: 'done' #完了画面に移動
# end
private
 def item_params
  # binding.pry
  params.require(:item).permit(:name, :price)
 end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.haml
=render partial: "questions/post"
.main-contents
  .choise-title
    質問の値段をえらんでください。
  -@items.each do |item|
    .main-contents__price
      =link_to item.name, item_purchase_index_path(item.id)

app/views/items/new.html.haml
-if current_user.email == "yujiasano@yujiasano"
  = form_for @item,url: {controller: 'items', action: 'create' } do |f|
    = f.text_field :name, placeholder: '質問の名前'
    = f.text_field :price, placeholder: '質問の値段'
    = f.submit "決定"

app/views/items/show.html.haml
%h2 購入を確定しますか？
%p Apple MacBook Pro 13インチ
%p ¥135,000(送料込み)
%br
%h3 支払い方法
- if @default_card_information.blank?
  %br /
- else
  -#以下カード情報を表示
  = "**** **** **** " + @default_card_information.last4
  - exp_month = @default_card_information.exp_month.to_s
  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
  = exp_month + " / " + exp_year
%br
= form_tag(pay_item_purchase_index_path(@item.id) , method: :post) do
  %button 購入する