config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'

  get 'purchase/done'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"

  resources :questions, only: [:index, :show, :new, :create, :destroy] do
    collection do
      get 'search'
    end
    resources :answers, only: [:create, :destroy] do
      resources :likes, only: [:create, :destroy]
    end
  end 
  resources :cards, only: [:new, :create] do
  end
  
  resources :items, only: [:index, :new, :show, :create] do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
 
  require "payjp" #PAYJPとやり取りするために、payjpをロード
  # カード登録のコントローラー
  def new
    # 後ほど、showアクション(登録クレジットカード詳細表示機能)実装時に追記します。
  end

  def create
    # 前回credentials.yml.encに記載したAPI秘密鍵を呼び出します。
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]

    # 後ほどトークン作成処理を行いますが、そちらの完了の有無でフラッシュメッセージを表示させます。
    # binding.pry
    if params["payjp_token"].blank?
      redirect_to root_path, alert: "クレジットカードを登録できませんでした。"
    else
    # 無事トークン作成された場合のアクション(こっちが本命のアクション)
    # まずは生成したトークンから、顧客情報と紐付け、PAY.JP管理サイトに登録
      customer = Payjp::Customer.create(
        # email: current_user.email,
        card: params["payjp_token"],
        metadata: {user_id: current_user.id} #最悪なくてもOK！
        
      )
      # 今度はトークン化した情報を自アプリのCredit_cardsテーブルに登録！
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      # 無事、トークン作成とともにcredit_cardsテーブルに登録された場合、createビューが表示されるように条件分岐
      if @card.save
        #もしcreateビューを作成しない場合はredirect_toなどで表示ビューを指定
        redirect_to items_path
      else
        redirect_to action: "create"
      end
    end
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
-# カード登録のビュー
-# cssは_new.scss
= render partial: 'questions/post'


.main-contents
  .card_add 
    .title= "質問の前にカードの登録が必要です！"
    .title2= "※本物のカード番号ではなく、必ずテストカードを使用してください。"
    =link_to "テストカードはこちら", "https://pay.jp/docs/testcard", :target=>["_blank"], class: "test"

    -#form_tagメソッドでcreateアクションに入力情報を渡します。
    = form_tag(cards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do
      .number-details
        .card-number カード番号
        %span.must_check 必須
      .number
        = text_field_tag 'payment_card_no', "", class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
      -# 事前にassets/imagesにcardsファイルを作成、中に各カード会社の画像を入れておき、呼び出す。
      .image
        = image_tag'cards.gif', size: "270x30", class: 'visa'
        -# = image_tag(image_path('cards/master.png'), class: 'master')
        -# = image_tag(image_path('cards/jcb.png'), class: 'jcb')
        -# = image_tag(image_path('cards/amex.png'), class: 'amex')
        -# = image_tag(image_path('cards/diners.png'), class: 'diners')
        -# = image_tag(image_path('cards/discover.png'), class: 'discover')

      .expirationdate
        .expirationdate__details
          .date 有効期限
          %span.must_check 必須
        .expirationdate__choice
          .month
            %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
              %option{value: "1"} 01
              %option{value: "2"} 02
              %option{value: "3"} 03
              %option{value: "4"} 04
              %option{value: "5"} 05
              %option{value: "6"} 06
              %option{value: "7"} 07
              %option{value: "8"} 08
              %option{value: "9"} 09
              %option{value: "10"} 10
              %option{value: "11"} 11
              %option{value: "12"} 12
            .month-details 月
          .year
            %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
              %option{value: "2020"} 20
              %option{value: "2021"} 21
              %option{value: "2022"} 22
              %option{value: "2023"} 23
              %option{value: "2024"} 24
              %option{value: "2025"} 25
              %option{value: "2026"} 26
              %option{value: "2027"} 27
              %option{value: "2028"} 28
              %option{value: "2029"} 29
              %option{value: "2030"} 30
            .year-details 年

      .securitycode
        .securitycode__details
          .securitycode-details__title セキュリティコード
          %span.must_check 必須
        .securitycode__cardsecurity
          = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
        -# .card-question カード裏面の番号とは？
      .add 
        = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button"